[skip ci] Try to fix Drupal install

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -40,6 +40,8 @@ variables:
   WEB_ROOT: "web"
   # Test unit folder relative to web root.
   UNIT_TEST_ROOT: "modules/custom"
+  # If you have a MySQL dump for testing to avoid installing.
+  UNIT_TEST_DUMP: "https://gitlab.com/mog33/gitlab-ci-drupal/uploads/13ca902a6988548f45b276389cbd3d42/dump.tar.xz"
   # Comma separated for phpqa and phpmetrics.
   PHP_CODE: "${WEB_ROOT}/modules/custom,${WEB_ROOT}/themes/custom"
   # Space separated for eslint and sass lint.
@@ -243,18 +245,21 @@ Build:
   except:
     - master
   after_script:
+    - cp ${CI_PROJECT_DIR}/config/settings.php ${WEB_ROOT}/sites/default/
     # If a dump exist from the cache of a previous build, we try to use it.
-    - cp ${CI_PROJECT_DIR}/config/settings.local.php ${WEB_ROOT}/sites/default/
-    - ./vendor/bin/drush site-install
-        --yes
-        --root "/var/www/html/web"
-        --db-url ${DB_URL}
-    # Create a db dump for next build.
-    - if [ ! -f ${CI_PROJECT_DIR}/dump/db_dump.sql ];
+    - if [ ! -f ${CI_PROJECT_DIR}/dump/dump.sql ];
       then
         mkdir -p dump;
-        ./vendor/bin/drush sql:dump
-          --result-file=${CI_PROJECT_DIR}/dump/db_dump.sql;
+        curl -L ${UNIT_TEST_DUMP} -o dump/dump.tar.xz -s;
+        tar xf dump/dump.tar.xz -C dump;
+      fi
+    # We import the dump, faster than a site install.
+    - if [ -f ${CI_PROJECT_DIR}/dump/dump.sql ];
+      then
+        mysql -hmariadb -uroot -proot drupal8 < ${CI_PROJECT_DIR}/dump/dump.sql;
+      else
+        echo "Missing database dump";
+        exit 1;
       fi
   # On build we cache the composer, web and dump folders.
   cache:
